// Renders the canonical TypeScript seed (src/lib/data/seed.ts) into
// supabase/seed.sql so the database seed never drifts from the app's seed.
// Run with: npm run seed:sql

import { writeFileSync } from "node:fs";
import { resolve } from "node:path";
import {
  airlineRules,
  airlines,
  carriers,
  merchantProducts,
  merchants,
  productCodes,
} from "../src/lib/data/seed";

function s(v: string | null | undefined): string {
  if (v == null) return "null";
  return `'${v.replace(/'/g, "''")}'`;
}
function n(v: number | null | undefined): string {
  return v == null ? "null" : String(v);
}
function b(v: boolean): string {
  return v ? "true" : "false";
}
function j(v: unknown): string {
  return `'${JSON.stringify(v).replace(/'/g, "''")}'::jsonb`;
}

const lines: string[] = [
  "-- GENERATED by scripts/generate-sql-seed.ts — do not edit by hand.",
  "-- Source of truth: src/lib/data/seed.ts",
  "begin;",
  "",
];

lines.push("-- airlines");
for (const a of airlines) {
  lines.push(
    `insert into public.airlines (id, name, iata, country) values (${s(a.id)}, ${s(a.name)}, ${s(a.iata)}, ${s(a.country)}) on conflict (id) do nothing;`,
  );
}

lines.push("", "-- carriers");
for (const c of carriers) {
  lines.push(
    `insert into public.carriers (id, brand, model, sku, soft_sided, length_cm, width_cm, height_cm, weight_kg, max_pet_weight_kg, verification, image_url, affiliate_url, affiliate_targets, price_usd, description) values (` +
      `${s(c.id)}, ${s(c.brand)}, ${s(c.model)}, ${s(c.sku)}, ${b(c.softSided)}, ${n(c.lengthCm)}, ${n(c.widthCm)}, ${n(c.heightCm)}, ${n(c.weightKg)}, ${n(c.maxPetWeightKg)}, ${s(c.verification)}, ${s(c.imageUrl)}, ${s(c.affiliateUrl)}, ${j(c.affiliateTargets ?? {})}, ${n(c.priceUsd)}, ${s(c.description)}) on conflict (id) do nothing;`,
  );
}

lines.push("", "-- airline_rules");
for (const r of airlineRules) {
  lines.push(
    `insert into public.airline_rules (id, airline_id, cabin, aircraft_type, max_length_cm, max_width_cm, max_height_cm, max_combined_weight_kg, soft_sided_requirement, aircraft_varies, notes, source_url, last_verified_at) values (` +
      `${s(r.id)}, ${s(r.airlineId)}, ${s(r.cabin)}, ${s(r.aircraftType)}, ${n(r.maxLengthCm)}, ${n(r.maxWidthCm)}, ${n(r.maxHeightCm)}, ${n(r.maxCombinedWeightKg)}, ${s(r.softSidedRequirement)}, ${b(r.aircraftVaries)}, ${s(r.notes)}, ${s(r.sourceUrl)}, ${s(r.lastVerifiedAt)}) on conflict (id) do nothing;`,
  );
}

lines.push("", "-- product_codes");
for (const p of productCodes) {
  lines.push(
    `insert into public.product_codes (code, carrier_id) values (${s(p.code)}, ${s(p.carrierId)}) on conflict (code) do nothing;`,
  );
}

lines.push("", "-- affiliate_targets");
for (const c of carriers) {
  for (const [network, url] of Object.entries(c.affiliateTargets ?? {})) {
    lines.push(
      `insert into public.affiliate_targets (carrier_id, network, url) values (${s(c.id)}, ${s(network)}, ${s(url)}) on conflict (carrier_id, network) do nothing;`,
    );
  }
}

lines.push("", "-- merchants");
for (const m of merchants) {
  lines.push(
    `insert into public.merchants (id, name, slug, website_url) values (${s(m.id)}, ${s(m.name)}, ${s(m.slug)}, ${s(m.websiteUrl)}) on conflict (id) do nothing;`,
  );
}

lines.push("", "-- merchant_products");
for (const mp of merchantProducts) {
  lines.push(
    `insert into public.merchant_products (id, merchant_id, carrier_id, external_product_id, product_url) values (${s(mp.id)}, ${s(mp.merchantId)}, ${s(mp.carrierId)}, ${s(mp.externalProductId)}, ${s(mp.productUrl)}) on conflict (id) do nothing;`,
  );
}

lines.push("", "commit;", "");

const out = resolve(process.cwd(), "supabase/seed.sql");
writeFileSync(out, lines.join("\n"), "utf8");
console.log(`Wrote ${out} (${carriers.length} carriers, ${airlines.length} airlines, ${airlineRules.length} rules).`);
